[package]
name = "xiv_craft_simulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strum_macros = "0.24"
strum = { version = "0.24", features = ["derive"] }
lazy_static = "1.4.0"
toml = "0.5.9"